### ISSUE TITLE
ControlFlowGraph plugin missing

### ISSUE THREAD

**Issue by riyadparvez** [avatarone/s2e-arm-testsuite#2]
Hi,

https://github.com/eurecom-s3/s2e-arm-testsuite/blob/master/tests/ControlFlowGraphPlugin/

There's been a test for testing ControlFlowGraph plugin, but I don't see any ControlFlowGraph plugin. Can you point where is ControlFlowGraph plugin implemented?

**Comment by zaddach** [comment]
Hi,

this is a mistake; the test for this plugin should not be there. It must have somehow slipped through from the internal repository. Do you need a control flow graph building for your project? We did not release the plugin up to now because in its current form it is not very helpful, i.e., Function calls are not recognized as such, returns (as indirect jumps) are not part of the CFG, etc.

Jonas

**Comment by riyadparvez** [comment]
Yes, I need CFG for my project. I will appreciate if you can release that plugin.

**Comment by zaddach** [comment]
I have pushed the commit on branch eurecom/avatar. Apart from all the other stuff I already said, be careful with multiple symbolic states ... this might or might not be handled well, depending if you have self-modifying code.

**Comment by riyadparvez** [comment]
Thanks! 
Do you have any idea how to get the CFG without using proprietary tools like IDA? Right now I'm considering getting the CFG from source code, then map instructions from binary to source line using `addr2line`. Is there a better approach?

**Comment by zaddach** [comment]
Hi,

yes, if you have the source, then just compile it to LLVM bitcode (clang
-emit-llvm) and run it through "opt -dot-cfg -dot-callgraph"(LLVM
toolsuite).
Though no idea how you get back from there to the source code line, but I'm
sure it's possible with the dwarf debug info in the .bc s ...

Jonas

P.s.: If you have a working system I'm interested in it too :)
One of my future projects would be a nice browser for LLVM code (and
possibly source code).

**Comment by riyadparvez** [comment]
Getting file name and line number from llvm bitcode should be easy, compile with debug symbols and optimization disabled. The following should work

```
  std::string getFilePath(DILocation Loc) {
    std::string dir = Loc.getDirectory();
    std::string file = Loc.getFilename();

    if (dir.empty() || file[0] == '/') {
      return file;
    } else if (*dir.rbegin() == '/') {
      return dir + file;
    } else {
      return dir + "/" + file;
    }
  }

  bool getInstructionSourceLocation(const llvm::Instruction *I,
                                    std::string &File,
                                    unsigned &Line) {
    if (MDNode *N = I->getMetadata("dbg")) {
      DILocation Loc(N);
      File = getFilePath(Loc);
      Line = Loc.getLineNumber();
      return true;
    }
    return false;
  }
```

My problem is I need CFG for Linux kernel which doesn't compile on clang.

**Comment by zaddach** [comment]
I managed to compile the kernel to bitcode, have a look at this [1] project.
You really need the most recent LLVM and Clang, Ubuntu 14.10 distro
packages did not work.
I use a simple wrapper script as compiler which builds the normal object,
and at the same time
the .bc. If you are interested, I can put it on Github.

May I ask what you want to do? (Just out of curiousity)

Jonas

[1] http://llvm.linuxfoundation.org/index.php/Main_Page

**Comment by riyadparvez** [comment]
I've tried llvmlinux. Do you know how much they have patched (not considering the patches accepted upstream) Linux kernel?

Did you compile single source file to bitcode or whole kernel module to bitcode? I have script for the first one; but I'll appreciate if you have script for second one.

Recent means llvm 3.5?

I want to run some static analysis on Linux kernel modules, that's why I need bitcode for whole module.

**Comment by zaddach** [comment]
Hi,

responses inline.

On Mon, Feb 23, 2015 at 8:55 AM, Riyad Parvez notifications@github.com
wrote:

> I've tried llvmlinux. Do you know how much they have patched (not
> considering the patches accepted upstream) Linux kernel?
> 
> No idea. But as far as I understood, they only changed expressions that are
> incompatible with clang, so the control flow SHOULD still be the same.
> 
> Did you compile single source file to bitcode or whole kernel module to
> bitcode? I have script for the first one; but I'll appreciate if you have
> script for second one.
> 
> My script recognizes if clang is called with "-c" or not, and invokes
> "clang -emit-llvm -c" or "llvm-link" accordingly (also there are some
> optimizations to weed out binary .o files generated)
> 
> Recent means llvm 3.5?
> 
> 3.5.1, that is the packets from LLVM's ppa.
> 
> I want to run some static analysis on Linux kernel modules, that's why I
> need bitcode for whole module.
> 
> That sounds interesting. Still, if you compile individual files and you
> link them with llvm-link, you should get something similar to the binary
> kernel module.

Jonas
